name: Robot Chụp Màn Hình Nhiệm Vụ

on:
  schedule:
    - cron: '30 4 * * *' # Chạy lúc 11:30 Trưa giờ Việt Nam (Tất cả các ngày trong tuần)
    - cron: '30 9 * * *' # Chạy lúc 16:30 Chiều giờ Việt Nam (Tất cả các ngày trong tuần)
  workflow_dispatch: # Nút bấm chạy bằng tay

jobs:
  run-robot:
    runs-on: ubuntu-latest

    steps:
    - name: Tải code về
      uses: actions/checkout@v4

    - name: Cài đặt Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cài đặt các thư viện cần thiết
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests

    - name: Kích hoạt Robot quét việc
      env:
        SKHCN_USER: ${{ secrets.SKHCN_USER }}
        SKHCN_PASS: ${{ secrets.SKHCN_PASS }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python robot.py
